---
# https://docs.travis-ci.com/user/customizing-the-build/
language: python
python:
  - "2.7"
  - "3.5"
#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U wheel
  - pip install -r requirements-dev.txt
  - pip install -e .[templates,repl]
script:
  - paver test
  - paver functest
  - paver installtest
